version: '3'
services:
    utest-microservice:
        container_name: utest-microservice
        build:
            context: .
            dockerfile: Dockerfile
        image: utest-microservice:latest
        ports:
            - 11111:11111
#        network_mode: "host"
#networks:
#  default:
#    external: true
#    name: ftgo-application_default