version: '3'
services:
  ftgo-api-gateway:
    image: uproxy:latest
    container_name: ftgo-api-gateway
    ports:
    - 8087:8080
    command: ["java","-Dserver.port=8087","-jar","/uproxy.jar", "ftgo-api-gateway",
      "host.docker.internal", "20011"]
  zookeeper-proxied:
    image: confluentinc/cp-zookeeper:5.2.4
    ports:
    - 20000:20000
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    command: ["java", "-Dserver.port=20000", "-Xmx200m",  "-jar", "/app/zookeeper-1.0.jar"]
  tcpdump:
    image: kaazing/tcpdump
    network_mode: host
    volumes:
    - ./tcpdump:/tcpdump
  ftgo-order-history-service:
    image: uproxy:latest
    container_name: ftgo-order-history-service
    ports:
    - 8086:8080
    command: ["java","-Dserver.port=8086","-jar","/uproxy.jar", "ftgo-order-history-service",
      "host.docker.internal", "20010"]
  zipkin-proxied:
    image: openzipkin/zipkin:2.5.0
    ports:
    - 20012:20012
    environment:
      JAVA_OPTS: -Xmx128m
    command: ["java", "-Dserver.port=20012", "-Xmx200m",  "-jar", "/app/zipkin-1.0.jar"]
  ftgo-order-history-service-proxied:
    build: ./ftgo-order-history-service
    ports:
    - 20010:20010
    depends_on:
    - kafka
    - zookeeper
    - cdc-service
    - dynamodblocal
    - dynamodblocal-init
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-id_key}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-access_key}
      AWS_DYNAMODB_ENDPOINT_URL: http://dynamodblocal:8000
      AWS_REGION: ${AWS_REGION:-us-west-2}
    command: ["java", "-Dserver.port=20010", "-Xmx200m",  "-jar", "/app/ftgo-order-history-service-1.0.jar"]
  ftgo-consumer-service:
    image: uproxy:latest
    container_name: ftgo-consumer-service
    ports:
    - 8081:8080
    command: ["java","-Dserver.port=8081","-jar","/uproxy.jar", "ftgo-consumer-service",
      "host.docker.internal", "20004"]
  ftgo-restaurant-service:
    image: uproxy:latest
    container_name: ftgo-restaurant-service
    ports:
    - 8084:8080
    command: ["java","-Dserver.port=8084","-jar","/uproxy.jar", "ftgo-restaurant-service",
      "host.docker.internal", "20007"]
  dynamodblocal:
    image: uproxy:latest
    container_name: dynamodblocal
    ports:
    - 8000:8000
    command: ["java","-Dserver.port=8000","-jar","/uproxy.jar", "dynamodblocal",
      "host.docker.internal", "20013"]
  mysql:
    image: uproxy:latest
    container_name: mysql
    ports:
    - 3306:3306
    command: ["java","-Dserver.port=3306","-jar","/uproxy.jar", "mysql", "host.docker.internal",
      "20002"]
  cdc-service-proxied:
    image: eventuateio/eventuate-cdc-service:0.6.0.RC3
    ports:
    - 20003:20003
    depends_on:
    - mysql
    - kafka
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATE_CDC_PIPELINE_PIPELINE1_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE1_READER: reader1
      EVENTUATE_CDC_PIPELINE_PIPELINE1_EVENTUATEDATABASESCHEMA: ftgo_consumer_service
      EVENTUATE_CDC_PIPELINE_PIPELINE2_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE2_READER: reader1
      EVENTUATE_CDC_PIPELINE_PIPELINE2_EVENTUATEDATABASESCHEMA: ftgo_order_service
      EVENTUATE_CDC_PIPELINE_PIPELINE3_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE3_READER: reader1
      EVENTUATE_CDC_PIPELINE_PIPELINE3_EVENTUATEDATABASESCHEMA: ftgo_kitchen_service
      EVENTUATE_CDC_PIPELINE_PIPELINE4_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE4_READER: reader1
      EVENTUATE_CDC_PIPELINE_PIPELINE4_EVENTUATEDATABASESCHEMA: ftgo_restaurant_service
      EVENTUATE_CDC_PIPELINE_PIPELINE5_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE5_READER: reader1
      EVENTUATE_CDC_PIPELINE_PIPELINE5_EVENTUATEDATABASESCHEMA: ftgo_accounting_service
      EVENTUATE_CDC_PIPELINE_PIPELINE6_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE6_READER: reader1
      EVENTUATE_CDC_PIPELINE_PIPELINE6_EVENTUATEDATABASESCHEMA: ftgoorderhistoryservice
      EVENTUATE_CDC_PIPELINE_PIPELINE7_TYPE: eventuate-local
      EVENTUATE_CDC_PIPELINE_PIPELINE7_READER: reader1
      EVENTUATE_CDC_PIPELINE_PIPELINE7_EVENTUATEDATABASESCHEMA: ftgo_accounting_service
      EVENTUATE_CDC_PIPELINE_PIPELINE8_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE8_READER: reader1
      EVENTUATE_CDC_PIPELINE_PIPELINE8_EVENTUATEDATABASESCHEMA: ftgo_delivery_service
      EVENTUATE_CDC_READER_READER1_TYPE: mysql-binlog
      EVENTUATE_CDC_READER_READER1_DATASOURCEURL: jdbc:mysql://mysql:3306/eventuate
      EVENTUATE_CDC_READER_READER1_DATASOURCEUSERNAME: root
      EVENTUATE_CDC_READER_READER1_DATASOURCEPASSWORD: rootpassword
      EVENTUATE_CDC_READER_READER1_DATASOURCEDRIVERCLASSNAME: com.mysql.jdbc.Driver
      EVENTUATE_CDC_READER_READER1_LEADERSHIPLOCKPATH: /eventuate/cdc/leader/common
      EVENTUATE_CDC_READER_READER1_CDCDBUSERNAME: root
      EVENTUATE_CDC_READER_READER1_CDCDBPASSWORD: rootpassword
      EVENTUATE_CDC_READER_READER1_READOLDDEBEZIUMDBOFFSETSTORAGETOPIC: 'false'
      EVENTUATE_CDC_READER_READER1_MYSQLBINLOGCLIENTUNIQUEID: 1
      EVENTUATE_CDC_READER_READER1_OFFSETSTOREKEY: MySqlBinlog
      EVENTUATE_CDC_READER_READER1_OFFSETSTORAGETOPICNAME: db.history.common
    command: ["java", "-Dserver.port=20003", "-Xmx200m",  "-jar", "/app/cdc-service-1.0.jar"]
  ftgo-delivery-service-proxied:
    build: ./ftgo-delivery-service
    ports:
    - 20009:20009
    depends_on:
    - mysql
    - kafka
    - cdc-service
    - zipkin
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/ftgo_delivery_service
      SPRING_DATASOURCE_USERNAME: ftgo_delivery_service_user
      SPRING_DATASOURCE_PASSWORD: ftgo_delivery_service_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      SPRING_SLEUTH_ENABLED: 'true'
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/
      EVENTUATE_DATABASE_SCHEMA: ftgo_delivery_service
    command: ["java", "-Dserver.port=20009", "-Xmx200m",  "-jar", "/app/ftgo-delivery-service-1.0.jar"]
  ftgo-accounting-service:
    image: uproxy:latest
    container_name: ftgo-accounting-service
    ports:
    - 8085:8080
    command: ["java","-Dserver.port=8085","-jar","/uproxy.jar", "ftgo-accounting-service",
      "host.docker.internal", "20008"]
  ftgo-kitchen-service-proxied:
    build: ./ftgo-kitchen-service
    ports:
    - 20006:20006
    depends_on:
    - mysql
    - kafka
    - zookeeper
    - cdc-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/ftgo_kitchen_service
      SPRING_DATASOURCE_USERNAME: ftgo_kitchen_service_user
      SPRING_DATASOURCE_PASSWORD: ftgo_kitchen_service_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATE_DATABASE_SCHEMA: ftgo_kitchen_service
    command: ["java", "-Dserver.port=20006", "-Xmx200m",  "-jar", "/app/ftgo-kitchen-service-1.0.jar"]
  ftgo-order-service-proxied:
    build: ./ftgo-order-service
    ports:
    - 20005:20005
    depends_on:
    - mysql
    - kafka
    - cdc-service
    - zipkin
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/ftgo_order_service
      SPRING_DATASOURCE_USERNAME: ftgo_order_service_user
      SPRING_DATASOURCE_PASSWORD: ftgo_order_service_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      SPRING_SLEUTH_ENABLED: 'true'
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/
      EVENTUATE_DATABASE_SCHEMA: ftgo_order_service
    command: ["java", "-Dserver.port=20005", "-Xmx200m",  "-jar", "/app/ftgo-order-service-1.0.jar"]
  ftgo-delivery-service:
    image: uproxy:latest
    container_name: ftgo-delivery-service
    ports:
    - 8089:8080
    command: ["java","-Dserver.port=8089","-jar","/uproxy.jar", "ftgo-delivery-service",
      "host.docker.internal", "20009"]
  mysql-proxied:
    build: ./mysql
    ports:
    - 20002:20002
    environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw
    command: ["java", "-Dserver.port=20002", "-Xmx200m",  "-jar", "/app/mysql-1.0.jar"]
  ftgo-api-gateway-proxied:
    build: ./ftgo-api-gateway
    ports:
    - 20011:20011
    environment:
      ORDER_DESTINATIONS_ORDERSERVICEURL: http://ftgo-order-service:8080
      ORDER_DESTINATIONS_ORDERHISTORYSERVICEURL: http://ftgo-order-history-service:8080
      CONSUMER_DESTINATIONS_CONSUMERSERVICEURL: http://ftgo-consumer-service:8080
      SPRING_SLEUTH_ENABLED: 'true'
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/
    command: ["java", "-Dserver.port=20011", "-Xmx200m",  "-jar", "/app/ftgo-api-gateway-1.0.jar"]
  zookeeper:
    image: uproxy:latest
    container_name: zookeeper
    ports:
    - 2181:2181
    command: ["java","-Dserver.port=2181","-jar","/uproxy.jar", "zookeeper", "host.docker.internal",
      "20000"]
  zipkin:
    image: uproxy:latest
    container_name: zipkin
    ports:
    - 9411:9411
    command: ["java","-Dserver.port=9411","-jar","/uproxy.jar", "zipkin", "host.docker.internal",
      "20012"]
  kafka-proxied:
    image: confluentinc/cp-kafka:5.2.4
    ports:
    - 20001:20001
    depends_on:
    - zookeeper
    environment:
      KAFKA_LISTENERS: LC://kafka:29092,LX://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LC:PLAINTEXT,LX:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LC
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    command: ["java", "-Dserver.port=20001", "-Xmx200m",  "-jar", "/app/kafka-1.0.jar"]
  ftgo-accounting-service-proxied:
    build: ./ftgo-accounting-service
    ports:
    - 20008:20008
    depends_on:
    - mysql
    - kafka
    - zookeeper
    - cdc-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/ftgo_accounting_service
      SPRING_DATASOURCE_USERNAME: ftgo_accounting_service_user
      SPRING_DATASOURCE_PASSWORD: ftgo_accounting_service_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATE_DATABASE_SCHEMA: ftgo_accounting_service
    command: ["java", "-Dserver.port=20008", "-Xmx200m",  "-jar", "/app/ftgo-accounting-service-1.0.jar"]
  ftgo-order-service:
    image: uproxy:latest
    container_name: ftgo-order-service
    ports:
    - 8082:8080
    command: ["java","-Dserver.port=8082","-jar","/uproxy.jar", "ftgo-order-service",
      "host.docker.internal", "20005"]
  dynamodblocal-init:
    build: ./dynamodblocal-init
    depends_on:
    - dynamodblocal
    restart: on-failure
    environment:
      AWS_DYNAMODB_ENDPOINT_URL: http://dynamodblocal:8000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-id_key}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-access_key}
      AWS_REGION: ${AWS_REGION:-us-west-2}
  dynamodblocal-proxied:
    build: ./dynamodblocal
    ports:
    - 20013:20013
    environment:
      JAVA_OPTS: -Xmx128m
    command: ["java", "-Dserver.port=20013", "-Xmx200m",  "-jar", "/app/dynamodblocal-1.0.jar"]
  ftgo-consumer-service-proxied:
    build: ./ftgo-consumer-service
    ports:
    - 20004:20004
    depends_on:
    - mysql
    - kafka
    - cdc-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/ftgo_consumer_service
      SPRING_DATASOURCE_USERNAME: ftgo_consumer_service_user
      SPRING_DATASOURCE_PASSWORD: ftgo_consumer_service_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATE_DATABASE_SCHEMA: ftgo_consumer_service
    command: ["java", "-Dserver.port=20004", "-Xmx200m",  "-jar", "/app/ftgo-consumer-service-1.0.jar"]
  kafka:
    image: uproxy:latest
    container_name: kafka
    ports:
    - 9092:9092
    command: ["java","-Dserver.port=9092","-jar","/uproxy.jar", "kafka", "host.docker.internal",
      "20001"]
  cdc-service:
    image: uproxy:latest
    container_name: cdc-service
    ports:
    - 8099:8080
    command: ["java","-Dserver.port=8099","-jar","/uproxy.jar", "cdc-service", "host.docker.internal",
      "20003"]
  ftgo-kitchen-service:
    image: uproxy:latest
    container_name: ftgo-kitchen-service
    ports:
    - 8083:8080
    command: ["java","-Dserver.port=8083","-jar","/uproxy.jar", "ftgo-kitchen-service",
      "host.docker.internal", "20006"]
  ftgo-restaurant-service-proxied:
    build: ./ftgo-restaurant-service
    ports:
    - 20007:20007
    depends_on:
    - mysql
    - kafka
    - zookeeper
    - cdc-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/ftgo_restaurant_service
      SPRING_DATASOURCE_USERNAME: ftgo_restaurant_service_user
      SPRING_DATASOURCE_PASSWORD: ftgo_restaurant_service_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATE_DATABASE_SCHEMA: ftgo_restaurant_service
    command: ["java", "-Dserver.port=20007", "-Xmx200m",  "-jar", "/app/ftgo-restaurant-service-1.0.jar"]
